---
name: CoreAPI
version: 0.0.1
main: JonasWindmann\CoreAPI\CoreAPI
api: 5.28.0
src-namespace-prefix: JonasWindmann\CoreAPI
description: A utility plugin that provides a set of APIs for PocketMine-MP plugin developers
website: https://github.com/DerCooleVonDem/CoreAPI
permissions:
  coreapi.admin:
    default: op
  coreapi.scoreboard.use:
    default: op
  coreapi.customitem.use:
    default: op
  coreapi.customitem.create:
    default: op
  coreapi.customitem.give:
    default: op
  coreapi.customitem.list:
    default: op
  coreapi.customitem.remove:
    default: op
  coreapi.customitem.info:
    default: op
  coreapi.customitem.export:
    default: op
  coreapi.customitem.import:
    default: op
  coreapi.npc.use:
    default: op
...
