---
name: CoreAPI
version: 0.0.1
main: JonasWindmann\CoreAPI\CoreAPI
api: 5.28.0
src-namespace-prefix: JonasWindmann\CoreAPI
description: A utility plugin that provides a set of APIs for PocketMine-MP plugin developers
website: https://github.com/JonasWindmann/CoreAPI
...
